### ISSUE TITLE
Entity Collider

### ISSUE THREAD

**Issue by edwinsyarief** [deepnight/gameBase#36]
Hi @deepnight ,

I don't have any idea where to set the collider:
![image](https://user-images.githubusercontent.com/13018338/115772932-e4653200-a3d9-11eb-8bc7-9c52912f292c.png)

My sample player can get through wall. I have also tried the default sample player:
![image](https://user-images.githubusercontent.com/13018338/115773538-a4527f00-a3da-11eb-8dd1-047f4d806dd6.png)

If I modified these lines:
```
// Ceiling collision
if (yr < 0.2 && level.hasCollision(cx, cy - 1)) {
	dy = 0;
	yr = 0.2;
}
```

into
```
// Ceiling collision
if (yr < 1.2 && level.hasCollision(cx, cy - 1)) {
	dy = 0;
	yr = 1.2;
}
```

Everything seems good, but there is a bug, this gif will explain better:
https://imgur.com/a/pu1gBXd

When I press right on the top corner, the player like stuck at the top corner.

Can you help?

Thank you.

**Comment by deepnight** [comment]
```haxe
// Ceiling collision
if (yr < 0.5 && level.hasCollision(cx, cy - 1)) {
	dy = 0;
	yr = 0.5; // value should be in 0 to 1 range
}
```

This code means: 
 - if there's a collision above me and **I'm in the first 50% part (0.5) of my current grid cell**, 
 - then cancel Y velocity, and make sure my position in current grid cell doesn't go lower than 50%.

Your 1.2 value doesn't make much sense because this would read "I'm in first 120% part of current grid cell"
